language: go
sudo: required

go:
- 1.11.1

stages:
  - name: build
  - name: deploy
    # only deploy if:
    ## we are not in a PR
    ## tag is blank (ie, master or any other branch)
    ## tag is a release tag (release/v1.6.1, which is the release build)
    if: (type != pull_request) AND ((tag IS blank) OR (tag =~ /^[\d\.]+(\-.*)?$/))

jobs:
  include:
    - stage: build
      env:
      - OPERATOR_VERSION="JOB_${TRAVIS_JOB_NUMBER}"
      name: "Build"
      install:
      - make install
      script:
      - make check
      - make build

    - stage: deploy
      name: "Publish release"
      env:
      - OPERATOR_VERSION="${TRAVIS_BRANCH}"
      script:
      - "./.travis/publish-images.sh"

    - stage: deploy
      name: "Release"
      env:
      - OPERATOR_VERSION="${TRAVIS_BRANCH}"
      script:
      - make build
      provider: releases
      api_key:
        secure: "JNoPrIDJhGT5g3J0X+6t00NAPRotzKrdhntK1fPaQmtn/7iL8/vKZ+81x2Fzo27vLFgC/y6Xjj3wqsV5u6sSY8v7fbSWm49sTHr/Hr1QNU/RSIb5EWqySnPpiWlZbsBZ8YYvFFLtu3Dh8FYa+KKNP9ScRsn9cxNJra5Fbnb8lirpkrD4TcgDg4r9V6JqeyXyMDjwLeBZwMuYAGQkJ+82/uIefeM5Bw1+B6oYJwtsLY49m5EGjVl/x2Jn/HSOlY6TgVGDTNWm1Y+WpGojLMx4HNFz5+LA7MEJr4QKYnndBUIFpQZ3iL0Qe4Z6L0WlEMSnXMBvDPvJDzDF3cGZy2WbdECU1Y5ZToBrpK8vjApNdNoLLnKvwdZnj2cABlv++TutXh7h94rdQRz+u9DgcNUlKdVrb+BJpnUObYg8bb5lXpQR6/SZD0tRXyswrCevH6OUgjBillPtU9Be2TCyPI4LwDXgdseUhs0N9JCeHehkM5SIxrqYeu3hsH0wES5FKFPgRomV/PJvTuDdYKXranV8ohxjFm/VzST/tPq95e8VGIi7h0sQjqX8nB6bDlU8BJi+2poEfmlNt7+nqJYxkTEQbQpgFezDbzkhgChAdsRnBtwCP7/oFqQ5ZG4wem+saN3Tb4Xi3iCSAWILLooHg+MrWx4NgJE1e02hXEWI6qY2Ogw="
      file: build/*
      skip_cleanup: true
      if: tag =~ /^[\d\.]+(\-.*)?$/
