// Code generated by "esc -pkg templates -o pkg/templates/gen_assets.go -ignore .go -prefix templates templates/all-labels.md templates/chrono-list.md templates/default-labels.md"; DO NOT EDIT.

package templates

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/all-labels.md": {
		name:    "all-labels.md",
		local:   "templates/all-labels.md",
		size:    543,
		modtime: 1558605256,
		compressed: `
H4sIAAAAAAAC/8yQwUrEMBCG73mKH7qHXdnmAQRB2YMeahGpeFg8ZNmxDaYN1ESQMO8uk1a2UB/A28zk
/2b4UuDQmaEl51ulUhqlhm5M+8msUiph33MLZlUUSEkaXZuekAOg4YySWWBM9OaDvvfYfBkXCdc30JU5
kaPztEJ25MjMz8yULhdHn6JzeXAlV6XTjQ1O7mJ7LH5n9xTq2J9oZH7bLoYPzWP18lwx7/Y43qakD77v
bdB3MXR+lETlWzvM1Orxgu+WlutS1MXq1YbOx4Ase/nJ2s/2f5nh36qVUjOrnwAAAP//bchC+h8CAAA=
`,
	},

	"/chrono-list.md": {
		name:    "chrono-list.md",
		local:   "templates/chrono-list.md",
		size:    296,
		modtime: 1558531006,
		compressed: `
H4sIAAAAAAAC/2SOT0sDMRDF7/kUQ/fSiglrD56VivWwFpH1VDxEOm4D+QMxexred5dgags9Je/NvHm/
jjZHGyf2aVJKJNc/mU0KwZUfQIloct9kRjsRoLqORKowOxuYAFqKtPXT8ziXY8rmyRY2zykHW2ix7vt7
3d/pfr0AVkqEOB7o4v7b7D1pQNFNbajSjK74v459d/K2XHZz+OIMfC4vzJfxdfh4H4DVLe0fzkwNZstl
SJOLLXU1PMf/4XSj43gA1G8AAAD//+lq5GEoAQAA
`,
	},

	"/default-labels.md": {
		name:    "default-labels.md",
		local:   "templates/default-labels.md",
		size:    1133,
		modtime: 1558615360,
		compressed: `
H4sIAAAAAAAC/+RST0s7MRC976cYmj20P9p8gB8I2iJ62BaReioeUneaDeaPpEm7Eua7S6LFFQ+911ve
m3nMe+ExWHTCStROVlVKPr+Br4XcE1UpzUDtCgSiijFIKQO+EgahLADaFmZEVcUYgxUeYYciRI/7PDyq
0EHdw/8rGCvbYg+8EVvU2MIIbSfsCxq0YTQBotPx+hXfp1AfhI6YhXUPAysPUety71/2khFfq6CzGxhv
2Im7w7CKZoue6Hk8IO/Xy+bpsSGaTGFznRJfOGNU4DcxdM7njcZJZb9Uv4bf8skwe0po25/fcSb87UWH
L12YRwk71eN+CktlnQdl3rw7lMxny7GN8u+VYn6RoYvhT/YjAAD///CChnptBAAA
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
